image: ghcr.io/dnj/php-alpine:8.0-mysql-nginx

stages:
  - test
  - deploy

composer-validate:
  stage: test
  before_script:
    - composer --version
  script:
    - composer validate

install-dependencies:
  stage: test
  cache:
    key:
      files:
        - composer.lock
        - composer.json
    paths:
      - vendor/
  script:
    - composer install --no-interaction

test-types:
  stage: test
  cache:
    key:
      files:
        - composer.lock
        - composer.json
    paths:
      - vendor/
    policy: pull
  dependencies:
    - install-dependencies
  script:
    - composer run test:types

test-codestyle:
  stage: test
  cache:
    key:
      files:
        - composer.lock
        - composer.json
    paths:
      - vendor/
    policy: pull
  dependencies:
    - install-dependencies
  script:
    - composer run test:codestyle

publish composer:
  image: curlimages/curl:latest
  stage: deploy
  script:
    - PACKAGE_VERSION=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data $PACKAGE_VERSION "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
