image: ghcr.io/dnj/php-alpine:8.0-mysql-nginx

stages:
  - test

composer-validate:
  stage: test
  before_script:
    - composer --version
  script:
    - composer validate

install-dependencies:
  stage: test
  cache:
    key:
      files:
        - composer.lock
        - composer.json
    paths:
      - vendor/
  script:
    - composer install --no-interaction

test-types:
  stage: test
  cache:
    key:
      files:
        - composer.lock
        - composer.json
    paths:
      - vendor/
    policy: pull
  dependencies:
    - install-dependencies
  script:
    - composer run test:types

test-codestyle:
  stage: test
  cache:
    key:
      files:
        - composer.lock
        - composer.json
    paths:
      - vendor/
    policy: pull
  dependencies:
    - install-dependencies
  script:
    - composer run test:codestyle
